In [2]:
import os
os.system('clear')
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
print(torch.__version__)


2.9.0.dev20250822+rocm6.4


In [3]:

##Introduction to tensor

### Creating tensor
## The first tensor that we are going to create it's called scalar, (é um 'vetor' sem índices)
## PyTorch tensor are created using 'torch.tensor()' https://docs.pytorch.org/docs/stable/tensors.html
scalar = torch.tensor(7)
print(scalar.ndim)

0


In [ ]:

#Get tensor back as python int
print(scalar.item())

In [ ]:
#Vector
vector = torch.tensor([7,7])
print(vector.ndim) # The command vector.ndim return's 1 as result, because [7,7] has just 1 bracket

print(vector.shape)
#But, vector.shape return's 2, because, there are 2 numbers inside the 1 bracket

In [ ]:

#Matrix
matrix = torch.tensor([
                       [7,8],
                       [9,10]
                       ])

print(matrix)
print(matrix.ndim)
print(matrix.shape)


In [ ]:

#TENSOR
TENSOR = torch.tensor([
                        [
                            [1,2,3],
                            [4,5,6],
                            [7,8,9]
                        ]
                    ])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
## Ao rodar o print(TENSOR.shape), ele retorn a'torch.Size([1,3,3])', o que a primeira momento
## se mostra estranho depois de se ter conhecimento de scalar,vetor e matrix, contudo, o
## '1' em [1,3,3] se refere ao primeiro par de [], que está indicando o número de matrizes,ou
## seja, 1 matrix 3x3, o primeiro '3' se refere ao número de linhas, e o último 3, se refere a
## o número de colunas

## É comum que ao escrever váriaveis que representem scalar() ou vetores()
## as escreva em lowercase, contudo, quando se escreve alguma váriavel que
## represente uma matrix() ou um tensor(), a coloque em uppercase

In [ ]:

### Random Tensor
"""
Why random tensors?

Random tensors are important because the way many neural networks learn is that
they start with tensor full of ramdom numbers and the adjust those random number
to better represent the data
 #ANCHOR: Start with random numbers -> look at data -> update random numbers -> look at data ->update random numbers
"""

# shape and size are the same thing to torch
#Creating a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
print(random_tensor)

#ANCHOR Creating a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour channels(R,GB), height,width
print(random_image_size_tensor.shape,random_image_size_tensor.ndim)
# print(random_image_size_tensor)

In [ ]:

#ANCHOR - Creating tensors of zero and one, it's usefull to create masks
zero = torch.zeros(size=(3,4))
print(zero)
print(zero * random_tensor)

#Creating a tensor full of ones
ones = torch.ones(size=(3,4))

print(ones.dtype)


#ANCHOR: Creating a range of tensor and tensor-like
one_to_ten = (torch.arange(start=1,end=11,step=1)) #https://docs.pytorch.org/docs/stable/generated/torch.arange.html
print(one_to_ten)


In [4]:

#ANCHOR -  Tensor datatypes
    #Float 32 tensor
    #!SECTION  Nota:
"""
    Nota: Os tipos de dados dos tensores, são um dos 3 principais erros que se é enfrentado
            ao usar PyTorch & Deep Learning
            1. Os tensores não estarem com o tipo certo de dado
            2. Os tensores não terem o shape/formato correto
            3. Os tensores não estarem no dispositivo correto
"""
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,# dtype define qual o tipo é o tensor(e.g float32 ou float16)
                               device = None,#EM que dispositivo está o seu tensor

                               requires_grad=False)# Se vai ou não, acompanhar os gradientes com as operações deste tensor

print(float_32_tensor)

tensor([3., 6., 9.])


In [5]:
float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor)

tensor([3., 6., 9.], dtype=torch.float16)


In [6]:
float_half_tensor = torch.tensor([12.0,15.0,18.0],dtype=torch.float16,device=None)
print(float_half_tensor)

tensor([12., 15., 18.], dtype=torch.float16)


In [7]:
print(float_16_tensor*float_32_tensor)

tensor([ 9., 36., 81.])


In [8]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
print(float_16_tensor*int_32_tensor)


tensor([ 9., 36., 81.], dtype=torch.float16)


### Getting informations from tensor
1. Os tensores não estarem com o tipo certo de dado - para achar o tipo do dado, se usa `tensor.dtype`
2. Os tensores não terem o shape/formato correto - para descobri o shape de um tensor, se usa `tensor.shape`
3. Os tensores não estarem no dispositivo correto - para descobrir o dispositivo de um tensor, se usa `tensor.device`

In [4]:
#Criando um tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5991, 0.8892, 0.8980, 0.3525],
        [0.1059, 0.3501, 0.3846, 0.1995],
        [0.3724, 0.5609, 0.1631, 0.1334]])

In [12]:
print(f"Data type of tensor:{some_tensor.dtype};")
print(f"Shape of tensor:{some_tensor.shape};")
print(f"Device tensor is on:{some_tensor.device};")

Data type of tensor:torch.float32;
Shape of tensor:torch.Size([3, 4]);
Device tensor is on:cpu;


In [22]:
some_tensor_zero = torch.zeros(size=(3,4))
print(f"Data type of tensor {some_tensor_zero.dtype}")
print(f"Shape of tensor {some_tensor_zero.shape}")
print(f"Device tensor is on {some_tensor_zero.device}")


Data type of tensor torch.float32
Shape of tensor torch.Size([3, 4])
Device tensor is on cpu


In [ ]:
###Manipulating Tensors (tensor operations)
Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [31]:
#Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3]) 
tensor + 10 # Ele acrescenta o valor a cada indice do tensor
#or
torch.add(tensor,10)

tensor([11, 12, 13])

In [25]:
#Multiply a tensor by ten
tensor * 10 # Ele multiplica o valor a cada indice do tensor

tensor([10, 20, 30])

In [26]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [28]:
# Using PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
#Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning:

Elemente-wise multiplication
Matrix Multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match: 
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimension**:
* `(2,3) @ (3,2) ` -> `(2,2)`




In [3]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.4105, 0.2254, 0.6899],
        [0.7380, 0.5004, 1.0374],
        [0.8256, 0.5365, 1.2100]])

In [32]:
#Element Wise Multiplication
print(tensor,"*",tensor )
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [33]:
#Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [34]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.64 ms, sys: 62 μs, total: 1.7 ms
Wall time: 37.8 ms


In [35]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 230 μs, sys: 22 μs, total: 252 μs
Wall time: 195 μs


tensor(14)

In [ ]:
### One of the most common erros in deep learning: shape errors 